services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    
    volumes:
      - mongo-hypoorbit-volume:/data/db
    restart: always

  backend-hypoorbit:
    container_name: backend-hypoorbit
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  front:
    container_name: front-hypoorbit
    build: ./frontend
    depends_on:
      - backend-hypoorbit
    env_file:
      - ./frontend/.env
    volumes:
      - hypoorbit-volume:/var/www/html
  
  nginx:
    container_name: nginx-hypoorbit
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - hypoorbit-volume:/var/www/html
    depends_on:
      - mongo
      - backend-hypoorbit
      - front

volumes:
  mongo-hypoorbit-volume:
  hypoorbit-volume: